// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWf7ghvtqi_1V26bMt-kftbFeKEXbBhQo',
    appId: '1:89780370025:android:d0d45fd198f7cae5ce80f8',
    messagingSenderId: '89780370025',
    projectId: 'mobileraker-ee176',
    storageBucket: 'mobileraker-ee176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzNXxjhlEWfAq6MNDIgY3BZ4coKlAang',
    appId: '1:89780370025:ios:654a5bea6b26b5fbce80f8',
    messagingSenderId: '89780370025',
    projectId: 'mobileraker-ee176',
    storageBucket: 'mobileraker-ee176.appspot.com',
    iosClientId: '89780370025-fkcr4srpcnka5bc7kj124g6g8tn08rie.apps.googleusercontent.com',
    iosBundleId: 'com.mobileraker.ios',
  );
}
